export const NAV_LIST = [
  {
    id: '0-0',
    refId: 'ref0-0',
    title: 'Menu',
    slug: '/menu',
    isAction: true,
    imageUrl: '',
  },
  {
    id: '0-1',
    refId: 'ref0-1',
    title: 'Search',
    slug: '/search',
    isAction: true,
    imageUrl: '',
  },
  {
    id: '0-2',
    refId: 'ref0-2',
    title: 'Cart',
    slug: '/cart',
    isAction: true,
    imageUrl: '',
  },
  {
    id: '0-3',
    refId: 'ref0-3',
    title: 'Headphones',
    slug: '/headphones',
    isAction: false,
    imageUrl: 'ath-adx5000_03.png',
  },
  {
    id: '0-4',
    refId: 'ref0-4',
    title: 'Speakers',
    slug: '/speakers',
    isAction: false,
    imageUrl: 'palatial-hero.png',
  },
  {
    id: '0-5',
    refId: 'ref0-5',
    title: 'Microphones',
    slug: '/microphones',
    isAction: false,
    imageUrl: 'at2050_02a.png',
  },
];
